//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::app_settings::Entity as AppSettings;
pub use super::runtime_heartbeats::Entity as RuntimeHeartbeats;
pub use super::users::Entity as Users;
